### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by UmerCodez** [JunkieLabs/sensify-android#3]
- App crashes on Redmi 4A **(Android 7.1.2)** on start up 
- Runs on Techno Camon 17 **(Android 12)** but crashes after few seconds while in use

**Comment by nirajprakash** [comment]
checking into it ..

**Comment by nirajprakash** [comment]
fixed in 3.0.9

**Comment by UmerCodez** [comment]
> fixed in 3.0.9

I Re installed the app from play store and it still crashes..

**Comment by nirajprakash** [comment]
This time different type of exception was there. Fixed in 3.0.10. 
Wait for 3.0.11 one more bug I have fixed in that.
